#!/usr/bin/env python
# Copyright (c) 2006, Sunjoong LEE <sunjoong@gmail.com> 
# Licensed under the Academic Free License version 3.0
# http://sunjoong.sourceforge.net/
__author__ = 'Sunjoong LEE <sunjoong@gmail.com>'
__date__ = '2006-06-24'
__version__ = '1.0.0'

from sunjoong.TMalignWrap import TMalignWrap
from sys import argv

TMalignWrap(argv)

